/**
 * Permission requirement per admin route name. Aligned with @Permissions in Api/Admin controllers.
 * - null: any authenticated admin user
 * - string: single permission (must pass hasPermission)
 * - { any: string[] }: user needs at least one of these (e.g. view vs list)
 */
export const ADMIN_ROUTE_PERMISSIONS = {
    'admin.dashboard': null,
    'admin.branch-select': null,
    'admin.workspace-setup': null,
    'admin.profile': null,
    'admin.setting': 'list_setting',
    'admin.general-settings': 'list_setting',
    'admin.security-settings': 'list_setting',
    'admin.notifications': 'list_setting',
    'admin.tax-list': 'list_tax',
    'admin.tax-group-list': 'list_tax',
    'admin.payment-mode-list': 'list_payment_mode',
    'admin.branch-list': 'list_branch',
    'admin.branch-users': 'list_branch',
    'admin.role-list': 'list_role',
    'admin.role-create': 'create_role',
    'admin.role-edit': 'edit_role',
    'admin.user-list': 'list_user',
    'admin.notification-list': null,
    'admin.reports-hub': null,
    'admin.sales-list': 'list_sales_order',
    'admin.invoice-list': 'list_invoice',
    'admin.invoice-view': { any: ['list_invoice', 'show_invoice'] },
    'admin.credit-note-list': 'list_credit_note',
    'admin.receipt-list': 'list_receipt',
    'admin.sales-returns': 'list_sales_order',
    'admin.quotation-list': 'list_quotation',
    'admin.sales-report': 'list_sales_order',
    'admin.sales-by-item': 'list_sales_order',
    'admin.brand-list': 'list_brand',
    'admin.unit-list': 'list_unit',
    'admin.warehouse-list': 'list_warehouse',
    'admin.stock-transfer': 'list_stock_transfer',
    'admin.stock-adjustment': 'list_stock_adjustment',
    'admin.opening-stock-entry': 'list_opening_stock_entry',
    'admin.product-category-list': 'list_product_category',
    'admin.product-create': 'create_product',
    'admin.product-edit': 'edit_product',
    'admin.product-list': 'list_product',
    'admin.data-transfer-list': 'list_data_transfer',
    'admin.crm-contacts': 'list_party',
    'admin.crm-follow-ups': 'list_crm_follow_up',
    'admin.crm-tasks': 'list_crm_task',
    'admin.crm-customer-profile': 'view_crm_customer_360',
    'admin.variant-attributes': 'list_attribute',
    'admin.barcode': 'list_product',
    'admin.purchase-list': 'list_purchase_order',
    'admin.purchase-order-list': 'list_purchase_order',
    'admin.bill-list': 'list_bill',
    'admin.expense-list': 'list_expense',
    'admin.payment-list': 'list_payment',
    'admin.debit-note-list': 'list_debit_note',
    'admin.purchase-report': 'list_bill',
    'admin.purchase-by-item': 'list_bill',
    'admin.chart-of-accounts': 'list_account',
    'admin.account-settings': 'list_account_setting',
    'admin.journal-voucher': 'list_journal_voucher',
    'admin.payment-voucher': 'list_payment_voucher',
    'admin.receipt-voucher': 'list_receipt_voucher',
    'admin.trial-balance': 'list_account',
    'admin.balance-sheet': 'list_account',
    'admin.profit-and-loss': 'list_account',
    'admin.journal-report': 'list_account',
    'admin.general-ledger': 'list_account',
    'admin.hr-employee-list': 'list_employee',
    'admin.hr-employee-create': 'create_employee',
    'admin.hr-employee-edit': 'edit_employee',
    'admin.hr-department-list': 'list_department',
    'admin.hr-designation-list': 'list_designation',
    'admin.hr-attendance': 'list_attendance',
    'admin.hr-leave-applications': 'list_leave_application',
    'admin.hr-leave-types': 'list_leave_type',
    'admin.hr-holidays': 'list_holiday',
    'admin.hr-salary-components': 'list_salary_component',
    'admin.hr-salary-structure': 'list_salary_structure',
    'admin.hr-payroll': 'list_payroll',
    'admin.hr-payroll-detail': { any: ['list_payroll', 'show_payroll'] },
    'admin.hr-payslip': { any: ['list_payroll', 'show_payroll'] },
    'admin.hr-report-payroll': 'list_payroll',
    'admin.hr-report-attendance': 'list_attendance',
    'admin.hr-report-leave': 'list_leave_application',
    'admin.hr-report-tds-salary': 'list_payroll',
    'admin.pos': 'list_product',

    // ── Guest / onboarding / static pages (any authenticated admin) ──
    'admin.login': null,
    'admin.register': null,
    'admin.forgot-password': null,
    'admin.onboarding': null,
    'admin.support': null,
    'admin.billing-pricing': null,

    // ── Sales reports ──
    'admin.sales-summary-report': 'sales_summary_report',
    'admin.daily-sales-report': 'daily_sales_report',
    'admin.monthly-sales-report': 'monthly_sales_report',
    'admin.yearly-sales-report': 'yearly_sales_report',
    'admin.customer-wise-sales-report': 'customer_wise_sales_report',
    'admin.category-wise-sales-report': 'category_wise_sales_report',
    'admin.product-wise-sales-report': 'product_wise_sales_report',
    'admin.sales-return-report': 'sales_return_report',
    'admin.outstanding-sales-report': 'outstanding_sales_report',
    'admin.sales-tax-report': 'sales_tax_report',
    'admin.sales-profit-report': 'sales_profit_report',
    'admin.discount-report': 'discount_report',
    'admin.sales-ledger-report': 'sales_ledger_report',
    'admin.customer-statement': 'sales_ledger_report',
    'admin.customer-transaction-report': 'sales_ledger_report',

    // ── Purchase reports ──
    'admin.purchase-summary-report': 'purchase_summary_report',
    'admin.daily-purchase-report': 'daily_purchase_report',
    'admin.monthly-purchase-report': 'monthly_purchase_report',
    'admin.yearly-purchase-report': 'yearly_purchase_report',
    'admin.supplier-wise-purchase-report': 'supplier_wise_purchase_report',
    'admin.category-wise-purchase-report': 'category_wise_purchase_report',
    'admin.purchase-return-report': 'purchase_return_report',
    'admin.outstanding-purchase-report': 'outstanding_purchase_report',
    'admin.purchase-tax-report': 'purchase_tax_report',
    'admin.purchase-ledger-report': 'purchase_ledger_report',
    'admin.grn-report': 'grn_report',
    'admin.pending-purchase-report': 'pending_purchase_report',
    'admin.purchase-discount-report': 'purchase_discount_report',
    'admin.supplier-statement': 'purchase_ledger_report',
    'admin.supplier-transaction-report': 'purchase_ledger_report',

    // ── Accounting / finance reports (backend report endpoints also accept list_account) ──
    'admin.cash-flow': 'list_account',
    'admin.ar-aging': 'list_account',
    'admin.ap-aging': 'list_account',
    'admin.cash-ledger-report': 'list_account',
    'admin.bank-ledger-report': 'list_account',
    'admin.daily-collection-report': 'list_account',
    'admin.daily-payment-report': 'list_account',
    'admin.cheque-issue-report': 'list_account',
    'admin.cheque-receive-report': 'list_account',
    'admin.payment-voucher-report': 'list_account',
    'admin.receipt-voucher-report': 'list_account',
    'admin.all-voucher-register': 'list_account',
    'admin.expense-statement-report': 'expense_statement_report',
    'admin.vat-sales-register': 'list_account',
    'admin.vat-purchase-register': 'list_account',
    'admin.vat-return': 'list_account',
    'admin.tds-report': 'list_account',
    'admin.tds-challan': 'list_account',
    'admin.ird-sync': { any: ['list_invoice', 'list_account'] },

    // ── Inventory reports (backend report endpoints also accept list_product / list_batch) ──
    'admin.inventory-valuation': 'list_product',
    'admin.stock-aging': 'list_product',
    'admin.reorder-alerts': 'list_product',
    'admin.stock-movement-report': 'list_product',
    'admin.stock-ledger-report': 'list_product',
    'admin.warehouse-stock-report': 'list_product',
    'admin.warehouse-transfer-report': 'list_product',
    'admin.expiry-stock-report': 'list_product',
    'admin.dead-stock-report': 'list_product',
    'admin.stock-opening-report': 'list_product',
    'admin.inventory-summary-report': 'inventory_summary_report',
    'admin.damage-stock-report': 'list_damage_report',
    'admin.production-variance-report': 'list_production_order',
    'admin.mrp-plan-report': 'list_production_order',
    'admin.batch-stock-report': 'list_batch',
    'admin.batch-traceability-report': 'list_batch',

    // ── Inventory / manufacturing management ──
    'admin.batch-list': 'list_batch',
    'admin.batch-create': 'create_batch',
    'admin.batch-edit': 'edit_batch',
    'admin.bom-list': 'list_bom',
    'admin.production-order-list': 'list_production_order',
    'admin.serial-numbers': 'list_serial_number',
    'admin.damage-report-list': 'list_damage_report',
    'admin.delivery-challan-list': 'list_delivery_challan',
    'admin.delivery-challan-create': 'create_delivery_challan',
    'admin.delivery-challan-view': 'show_delivery_challan',
    'admin.grn-list': 'list_grn',
    'admin.grn-create': 'create_grn',
    'admin.grn-view': 'show_grn',
    'admin.product-show': { any: ['list_product', 'show_product'] },
    'admin.stock-reconciliation': 'list_stock_adjustment',

    // ── Accounting management ──
    'admin.accounting-periods': 'list_accounting_period',
    'admin.opening-balances': 'list_journal_voucher',
    'admin.recurring-journal-list': 'list_recurring_journal',
    'admin.budget-list': 'list_budget',
    'admin.fixed-asset-list': 'list_fixed_asset',
    'admin.cheque-list': 'list_cheque',
    'admin.bank-reconciliation': 'list_bank_account',
    'admin.cash-flow-forecast': 'view_cash_flow_forecast',
    'admin.branch-pl': 'list_branch',
    'admin.ird-settings': { any: ['list_invoice', 'edit_setting'] },

    // ── HR ──
    'admin.hr-employee-salary-ledger': 'list_payroll',
    'admin.hr-work-schedule': 'show_work_schedule',
};

/**
 * @param {string|undefined} routeName
 * @returns {null|string|{any: string[]}|undefined} undefined = not in map (do not enforce)
 */
export function getAdminRoutePermission(routeName) {
    if (!routeName) return undefined;
    return Object.prototype.hasOwnProperty.call(
        ADMIN_ROUTE_PERMISSIONS,
        routeName
    )
        ? ADMIN_ROUTE_PERMISSIONS[routeName]
        : undefined;
}
